### ISSUE TITLE
Frequency of drone position update

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/hydra-flock-gui#3]
How frequently should we update the drone positions on the UI. I think 1 second is a good number, what do you guys think @chrizandr @Mec-iS @kkoci ?

**Comment by kkoci** [comment]
I think 1 sec is fair enough, but as I said earlier, we'll try to avoid lag, so maybe we'll have to test it

**Comment by Mec-iS** [comment]
As by design, 15 secs loops.

**Comment by xadahiya** [comment]
@Mec-iS Won't 15 seconds be too slow for UI updates?

**Comment by Mec-iS** [comment]
It depends from the zoom and the total area and the relative velocity of a drone. On a 12 zoom map a drone will look on the same position for a frequency of 1 sec (because of its limited speed). 
Btw it can be solved by using blinking markers, these things can be tweaked and adjusted afterwards. Optimization after, implementation first.

**Comment by xadahiya** [comment]
Okay, Cool 👍

**Comment by xadahiya** [comment]
Done
